[Leshan] Remove travis and make changes to use github actions
dojot/iotagent-leshan pull request #92
Opened 2021-02-08 16:33 UTC by marianoleonardo

dojot/dojot#1913

2021-02-08 16:58 UTC, mprevide approved these changes

2021-02-08 19:07 UTC, thiagodpf submitted a review, later dismissed

2021-02-09 20:28 UTC, mprevide requested changes
I left a comment

2021-02-09 20:28 UTC, mprevide commented on .github/workflows/main.yml
> +        name: ${{ steps.get_owner.outputs.owner }}/leshan
I think that name is wrong. Check in Docker-compose or Ansible

2021-02-19 16:16 UTC, mprevide approved these changes

2021-02-22 11:23 UTC, thiagodpf approved these changes

2021-02-22 12:25 UTC, merged